'use client'
import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'
import { ArrowRight, LoaderCircle } from 'lucide-react'

export function AuthForm({ mode }: { mode: 'sign-in' | 'sign-up' }) {
  const router = useRouter(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const signUp = mode === 'sign-up'
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(''); const result = signUp ? await authClient.signUp.email({ name, email, password }) : await authClient.signIn.email({ email, password }); setLoading(false); if (result.error) return setError(result.error.message || 'Unable to continue'); router.push('/'); router.refresh() }
  return <main className="auth-shell"><section className="auth-panel"><Link href="/" className="font-mono text-xl font-black italic">REDLINE</Link><div className="flex flex-col gap-2"><p className="eyebrow">2026 PREDICTION CHAMPIONSHIP</p><h1 className="text-balance font-mono text-4xl font-black uppercase italic">{signUp ? 'Join the grid' : 'Back on track'}</h1><p className="text-muted-foreground">{signUp ? 'Create your profile and start making picks.' : 'Sign in to manage your race weekend predictions.'}</p></div><form onSubmit={submit} className="flex flex-col gap-4">{signUp && <label className="field">Display name<input value={name} onChange={(e) => setName(e.target.value)} required autoComplete="name" /></label>}<label className="field">Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></label><label className="field">Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={8} autoComplete={signUp ? 'new-password' : 'current-password'} /></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<button className="button-primary h-12" disabled={loading}>{loading ? <LoaderCircle className="animate-spin" aria-label="Loading" /> : <>{signUp ? 'Create account' : 'Sign in'}<ArrowRight aria-hidden="true" /></>}</button></form><p className="text-sm text-muted-foreground">{signUp ? 'Already racing? ' : 'New to Redline? '}<Link className="font-bold text-foreground underline" href={signUp ? '/sign-in' : '/sign-up'}>{signUp ? 'Sign in' : 'Create account'}</Link></p></section><aside className="auth-art" aria-hidden="true"><div className="speed-lines" /><p className="font-mono text-8xl font-black italic text-primary">01</p><p className="max-w-sm text-3xl font-bold text-primary-foreground">Every position. Every point. Every race.</p></aside></main>
}
